// flow-typed signature: cb783c5c3110b2281f48908b52ef6925
// flow-typed version: <<STUB>>/@fortawesome/fontawesome-svg-core_v^1.2.26/flow_v0.116.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@fortawesome/fontawesome-svg-core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@fortawesome/fontawesome-svg-core' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@fortawesome/fontawesome-svg-core/index.es' {
  declare module.exports: any;
}

// Filename aliases
declare module '@fortawesome/fontawesome-svg-core/index.es.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-svg-core/index.es'>;
}
declare module '@fortawesome/fontawesome-svg-core/index' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-svg-core'>;
}
declare module '@fortawesome/fontawesome-svg-core/index.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-svg-core'>;
}
