// flow-typed signature: 3c77612020920ebaec904038dcf2f337
// flow-typed version: <<STUB>>/@types/reach__router_v^1.2.6/flow_v0.116.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/reach__router'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/reach__router' {
  declare module.exports: any;
}
