// flow-typed signature: 36d289507a1fd01b18721dfa46c6c1e1
// flow-typed version: <<STUB>>/cp_v^0.2.0/flow_v0.116.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'cp/index' {
  declare module.exports: $Exports<'cp'>;
}
declare module 'cp/index.js' {
  declare module.exports: $Exports<'cp'>;
}
