// flow-typed signature: ab4b36373ca236ac475621e8714f4c21
// flow-typed version: <<STUB>>/cypress-pipe_v^1.6.0/flow_v0.116.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cypress-pipe'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cypress-pipe' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'cypress-pipe/index' {
  declare module.exports: $Exports<'cypress-pipe'>;
}
declare module 'cypress-pipe/index.js' {
  declare module.exports: $Exports<'cypress-pipe'>;
}
