// flow-typed signature: 6be9e20c6bca4778b566279beaf0a975
// flow-typed version: <<STUB>>/cypress-parcel-preprocessor_v^1.0.0/flow_v0.116.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cypress-parcel-preprocessor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cypress-parcel-preprocessor' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cypress-parcel-preprocessor/src' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cypress-parcel-preprocessor/src/index' {
  declare module.exports: $Exports<'cypress-parcel-preprocessor/src'>;
}
declare module 'cypress-parcel-preprocessor/src/index.js' {
  declare module.exports: $Exports<'cypress-parcel-preprocessor/src'>;
}
