// flow-typed signature: 973ffd6c05a6b1b5885df18cca1571cd
// flow-typed version: <<STUB>>/cypress-jest-adapter_v^0.1.1/flow_v0.116.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cypress-jest-adapter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cypress-jest-adapter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cypress-jest-adapter/dist' {
  declare module.exports: any;
}

declare module 'cypress-jest-adapter/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cypress-jest-adapter/dist/index' {
  declare module.exports: $Exports<'cypress-jest-adapter/dist'>;
}
declare module 'cypress-jest-adapter/dist/index.js' {
  declare module.exports: $Exports<'cypress-jest-adapter/dist'>;
}
declare module 'cypress-jest-adapter/webpack.config.js' {
  declare module.exports: $Exports<'cypress-jest-adapter/webpack.config'>;
}
