// flow-typed signature: 3f084dcb8262349da3e7a5b2343fef80
// flow-typed version: <<STUB>>/express-list-endpoints_v^4.0.1/flow_v0.116.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-list-endpoints'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-list-endpoints' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'express-list-endpoints/src' {
  declare module.exports: any;
}

// Filename aliases
declare module 'express-list-endpoints/src/index' {
  declare module.exports: $Exports<'express-list-endpoints/src'>;
}
declare module 'express-list-endpoints/src/index.js' {
  declare module.exports: $Exports<'express-list-endpoints/src'>;
}
