// flow-typed signature: e9b4cc807bf7620e60356591253057dc
// flow-typed version: <<STUB>>/fibers_v^4.0.2/flow_v0.116.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fibers'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fibers' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fibers/build' {
  declare module.exports: any;
}

declare module 'fibers/fibers' {
  declare module.exports: any;
}

declare module 'fibers/future' {
  declare module.exports: any;
}

declare module 'fibers/quick-test' {
  declare module.exports: any;
}

declare module 'fibers/test' {
  declare module.exports: any;
}

declare module 'fibers/test/already-running' {
  declare module.exports: any;
}

declare module 'fibers/test/async-hooks' {
  declare module.exports: any;
}

declare module 'fibers/test/bad-context' {
  declare module.exports: any;
}

declare module 'fibers/test/child-process' {
  declare module.exports: any;
}

declare module 'fibers/test/cleanup' {
  declare module.exports: any;
}

declare module 'fibers/test/current' {
  declare module.exports: any;
}

declare module 'fibers/test/exec' {
  declare module.exports: any;
}

declare module 'fibers/test/exit' {
  declare module.exports: any;
}

declare module 'fibers/test/fibonacci' {
  declare module.exports: any;
}

declare module 'fibers/test/finish-multiple' {
  declare module.exports: any;
}

declare module 'fibers/test/future-exception' {
  declare module.exports: any;
}

declare module 'fibers/test/future' {
  declare module.exports: any;
}

declare module 'fibers/test/illegal-yield' {
  declare module.exports: any;
}

declare module 'fibers/test/pool' {
  declare module.exports: any;
}

declare module 'fibers/test/process-title' {
  declare module.exports: any;
}

declare module 'fibers/test/stack-overflow' {
  declare module.exports: any;
}

declare module 'fibers/test/stack-overflow2' {
  declare module.exports: any;
}

declare module 'fibers/test/started' {
  declare module.exports: any;
}

declare module 'fibers/test/unwind' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fibers/build.js' {
  declare module.exports: $Exports<'fibers/build'>;
}
declare module 'fibers/fibers.js' {
  declare module.exports: $Exports<'fibers/fibers'>;
}
declare module 'fibers/future.js' {
  declare module.exports: $Exports<'fibers/future'>;
}
declare module 'fibers/quick-test.js' {
  declare module.exports: $Exports<'fibers/quick-test'>;
}
declare module 'fibers/test.js' {
  declare module.exports: $Exports<'fibers/test'>;
}
declare module 'fibers/test/already-running.js' {
  declare module.exports: $Exports<'fibers/test/already-running'>;
}
declare module 'fibers/test/async-hooks.js' {
  declare module.exports: $Exports<'fibers/test/async-hooks'>;
}
declare module 'fibers/test/bad-context.js' {
  declare module.exports: $Exports<'fibers/test/bad-context'>;
}
declare module 'fibers/test/child-process.js' {
  declare module.exports: $Exports<'fibers/test/child-process'>;
}
declare module 'fibers/test/cleanup.js' {
  declare module.exports: $Exports<'fibers/test/cleanup'>;
}
declare module 'fibers/test/current.js' {
  declare module.exports: $Exports<'fibers/test/current'>;
}
declare module 'fibers/test/exec.js' {
  declare module.exports: $Exports<'fibers/test/exec'>;
}
declare module 'fibers/test/exit.js' {
  declare module.exports: $Exports<'fibers/test/exit'>;
}
declare module 'fibers/test/fibonacci.js' {
  declare module.exports: $Exports<'fibers/test/fibonacci'>;
}
declare module 'fibers/test/finish-multiple.js' {
  declare module.exports: $Exports<'fibers/test/finish-multiple'>;
}
declare module 'fibers/test/future-exception.js' {
  declare module.exports: $Exports<'fibers/test/future-exception'>;
}
declare module 'fibers/test/future.js' {
  declare module.exports: $Exports<'fibers/test/future'>;
}
declare module 'fibers/test/illegal-yield.js' {
  declare module.exports: $Exports<'fibers/test/illegal-yield'>;
}
declare module 'fibers/test/pool.js' {
  declare module.exports: $Exports<'fibers/test/pool'>;
}
declare module 'fibers/test/process-title.js' {
  declare module.exports: $Exports<'fibers/test/process-title'>;
}
declare module 'fibers/test/stack-overflow.js' {
  declare module.exports: $Exports<'fibers/test/stack-overflow'>;
}
declare module 'fibers/test/stack-overflow2.js' {
  declare module.exports: $Exports<'fibers/test/stack-overflow2'>;
}
declare module 'fibers/test/started.js' {
  declare module.exports: $Exports<'fibers/test/started'>;
}
declare module 'fibers/test/unwind.js' {
  declare module.exports: $Exports<'fibers/test/unwind'>;
}
