// flow-typed signature: a11f16b0f9201690e479f270ce5211d9
// flow-typed version: <<STUB>>/jest-haste-map_v^24.9.0/flow_v0.116.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-haste-map'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-haste-map' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-haste-map/build/blacklist' {
  declare module.exports: any;
}

declare module 'jest-haste-map/build/constants' {
  declare module.exports: any;
}

declare module 'jest-haste-map/build/crawlers/node' {
  declare module.exports: any;
}

declare module 'jest-haste-map/build/crawlers/watchman' {
  declare module.exports: any;
}

declare module 'jest-haste-map/build/getMockName' {
  declare module.exports: any;
}

declare module 'jest-haste-map/build/HasteFS' {
  declare module.exports: any;
}

declare module 'jest-haste-map/build' {
  declare module.exports: any;
}

declare module 'jest-haste-map/build/lib/dependencyExtractor' {
  declare module.exports: any;
}

declare module 'jest-haste-map/build/lib/fast_path' {
  declare module.exports: any;
}

declare module 'jest-haste-map/build/lib/FSEventsWatcher' {
  declare module.exports: any;
}

declare module 'jest-haste-map/build/lib/getPlatformExtension' {
  declare module.exports: any;
}

declare module 'jest-haste-map/build/lib/isRegExpSupported' {
  declare module.exports: any;
}

declare module 'jest-haste-map/build/lib/normalizePathSep' {
  declare module.exports: any;
}

declare module 'jest-haste-map/build/lib/WatchmanWatcher' {
  declare module.exports: any;
}

declare module 'jest-haste-map/build/ModuleMap' {
  declare module.exports: any;
}

declare module 'jest-haste-map/build/types' {
  declare module.exports: any;
}

declare module 'jest-haste-map/build/worker' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-haste-map/build/blacklist.js' {
  declare module.exports: $Exports<'jest-haste-map/build/blacklist'>;
}
declare module 'jest-haste-map/build/constants.js' {
  declare module.exports: $Exports<'jest-haste-map/build/constants'>;
}
declare module 'jest-haste-map/build/crawlers/node.js' {
  declare module.exports: $Exports<'jest-haste-map/build/crawlers/node'>;
}
declare module 'jest-haste-map/build/crawlers/watchman.js' {
  declare module.exports: $Exports<'jest-haste-map/build/crawlers/watchman'>;
}
declare module 'jest-haste-map/build/getMockName.js' {
  declare module.exports: $Exports<'jest-haste-map/build/getMockName'>;
}
declare module 'jest-haste-map/build/HasteFS.js' {
  declare module.exports: $Exports<'jest-haste-map/build/HasteFS'>;
}
declare module 'jest-haste-map/build/index' {
  declare module.exports: $Exports<'jest-haste-map/build'>;
}
declare module 'jest-haste-map/build/index.js' {
  declare module.exports: $Exports<'jest-haste-map/build'>;
}
declare module 'jest-haste-map/build/lib/dependencyExtractor.js' {
  declare module.exports: $Exports<'jest-haste-map/build/lib/dependencyExtractor'>;
}
declare module 'jest-haste-map/build/lib/fast_path.js' {
  declare module.exports: $Exports<'jest-haste-map/build/lib/fast_path'>;
}
declare module 'jest-haste-map/build/lib/FSEventsWatcher.js' {
  declare module.exports: $Exports<'jest-haste-map/build/lib/FSEventsWatcher'>;
}
declare module 'jest-haste-map/build/lib/getPlatformExtension.js' {
  declare module.exports: $Exports<'jest-haste-map/build/lib/getPlatformExtension'>;
}
declare module 'jest-haste-map/build/lib/isRegExpSupported.js' {
  declare module.exports: $Exports<'jest-haste-map/build/lib/isRegExpSupported'>;
}
declare module 'jest-haste-map/build/lib/normalizePathSep.js' {
  declare module.exports: $Exports<'jest-haste-map/build/lib/normalizePathSep'>;
}
declare module 'jest-haste-map/build/lib/WatchmanWatcher.js' {
  declare module.exports: $Exports<'jest-haste-map/build/lib/WatchmanWatcher'>;
}
declare module 'jest-haste-map/build/ModuleMap.js' {
  declare module.exports: $Exports<'jest-haste-map/build/ModuleMap'>;
}
declare module 'jest-haste-map/build/types.js' {
  declare module.exports: $Exports<'jest-haste-map/build/types'>;
}
declare module 'jest-haste-map/build/worker.js' {
  declare module.exports: $Exports<'jest-haste-map/build/worker'>;
}
