// flow-typed signature: 995e3515a8b6339b1b1bbb1d46edfa56
// flow-typed version: <<STUB>>/react-clamp-lines_v^3.0.2/flow_v0.116.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-clamp-lines'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-clamp-lines' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-clamp-lines/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-clamp-lines/lib/index' {
  declare module.exports: $Exports<'react-clamp-lines/lib'>;
}
declare module 'react-clamp-lines/lib/index.js' {
  declare module.exports: $Exports<'react-clamp-lines/lib'>;
}
