// flow-typed signature: db42fcb987c1271483348a66187ab961
// flow-typed version: <<STUB>>/@blueprintjs/icons_v^3.13.0/flow_v0.116.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@blueprintjs/icons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@blueprintjs/icons' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@blueprintjs/icons/dist/icons.bundle' {
  declare module.exports: any;
}

declare module '@blueprintjs/icons/lib/cjs/generated/iconContents' {
  declare module.exports: any;
}

declare module '@blueprintjs/icons/lib/cjs/generated/iconNames' {
  declare module.exports: any;
}

declare module '@blueprintjs/icons/lib/cjs/generated/iconSvgPaths' {
  declare module.exports: any;
}

declare module '@blueprintjs/icons/lib/cjs/iconName' {
  declare module.exports: any;
}

declare module '@blueprintjs/icons/lib/cjs' {
  declare module.exports: any;
}

declare module '@blueprintjs/icons/lib/esm/generated/iconContents' {
  declare module.exports: any;
}

declare module '@blueprintjs/icons/lib/esm/generated/iconNames' {
  declare module.exports: any;
}

declare module '@blueprintjs/icons/lib/esm/generated/iconSvgPaths' {
  declare module.exports: any;
}

declare module '@blueprintjs/icons/lib/esm/iconName' {
  declare module.exports: any;
}

declare module '@blueprintjs/icons/lib/esm' {
  declare module.exports: any;
}

declare module '@blueprintjs/icons/lib/esnext/generated/iconContents' {
  declare module.exports: any;
}

declare module '@blueprintjs/icons/lib/esnext/generated/iconNames' {
  declare module.exports: any;
}

declare module '@blueprintjs/icons/lib/esnext/generated/iconSvgPaths' {
  declare module.exports: any;
}

declare module '@blueprintjs/icons/lib/esnext/iconName' {
  declare module.exports: any;
}

declare module '@blueprintjs/icons/lib/esnext' {
  declare module.exports: any;
}

// Filename aliases
declare module '@blueprintjs/icons/dist/icons.bundle.js' {
  declare module.exports: $Exports<'@blueprintjs/icons/dist/icons.bundle'>;
}
declare module '@blueprintjs/icons/lib/cjs/generated/iconContents.js' {
  declare module.exports: $Exports<'@blueprintjs/icons/lib/cjs/generated/iconContents'>;
}
declare module '@blueprintjs/icons/lib/cjs/generated/iconNames.js' {
  declare module.exports: $Exports<'@blueprintjs/icons/lib/cjs/generated/iconNames'>;
}
declare module '@blueprintjs/icons/lib/cjs/generated/iconSvgPaths.js' {
  declare module.exports: $Exports<'@blueprintjs/icons/lib/cjs/generated/iconSvgPaths'>;
}
declare module '@blueprintjs/icons/lib/cjs/iconName.js' {
  declare module.exports: $Exports<'@blueprintjs/icons/lib/cjs/iconName'>;
}
declare module '@blueprintjs/icons/lib/cjs/index' {
  declare module.exports: $Exports<'@blueprintjs/icons/lib/cjs'>;
}
declare module '@blueprintjs/icons/lib/cjs/index.js' {
  declare module.exports: $Exports<'@blueprintjs/icons/lib/cjs'>;
}
declare module '@blueprintjs/icons/lib/esm/generated/iconContents.js' {
  declare module.exports: $Exports<'@blueprintjs/icons/lib/esm/generated/iconContents'>;
}
declare module '@blueprintjs/icons/lib/esm/generated/iconNames.js' {
  declare module.exports: $Exports<'@blueprintjs/icons/lib/esm/generated/iconNames'>;
}
declare module '@blueprintjs/icons/lib/esm/generated/iconSvgPaths.js' {
  declare module.exports: $Exports<'@blueprintjs/icons/lib/esm/generated/iconSvgPaths'>;
}
declare module '@blueprintjs/icons/lib/esm/iconName.js' {
  declare module.exports: $Exports<'@blueprintjs/icons/lib/esm/iconName'>;
}
declare module '@blueprintjs/icons/lib/esm/index' {
  declare module.exports: $Exports<'@blueprintjs/icons/lib/esm'>;
}
declare module '@blueprintjs/icons/lib/esm/index.js' {
  declare module.exports: $Exports<'@blueprintjs/icons/lib/esm'>;
}
declare module '@blueprintjs/icons/lib/esnext/generated/iconContents.js' {
  declare module.exports: $Exports<'@blueprintjs/icons/lib/esnext/generated/iconContents'>;
}
declare module '@blueprintjs/icons/lib/esnext/generated/iconNames.js' {
  declare module.exports: $Exports<'@blueprintjs/icons/lib/esnext/generated/iconNames'>;
}
declare module '@blueprintjs/icons/lib/esnext/generated/iconSvgPaths.js' {
  declare module.exports: $Exports<'@blueprintjs/icons/lib/esnext/generated/iconSvgPaths'>;
}
declare module '@blueprintjs/icons/lib/esnext/iconName.js' {
  declare module.exports: $Exports<'@blueprintjs/icons/lib/esnext/iconName'>;
}
declare module '@blueprintjs/icons/lib/esnext/index' {
  declare module.exports: $Exports<'@blueprintjs/icons/lib/esnext'>;
}
declare module '@blueprintjs/icons/lib/esnext/index.js' {
  declare module.exports: $Exports<'@blueprintjs/icons/lib/esnext'>;
}
