// flow-typed signature: 508c352e7343debb58e9bb168ea23deb
// flow-typed version: <<STUB>>/@blueprintjs/table_v^3.8.2/flow_v0.116.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@blueprintjs/table'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@blueprintjs/table' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@blueprintjs/table/dist/table.bundle' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/cjs/cell/cell' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/cjs/cell/editableCell' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/cjs/cell/formats/jsonFormat' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/cjs/cell/formats/truncatedFormat' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/cjs/column' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/cjs/common/batcher' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/cjs/common/cell' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/cjs/common/classes' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/cjs/common/clipboard' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/cjs/common/context' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/cjs/common/contextMenuTargetWrapper' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/cjs/common/direction' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/cjs/common/errors' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/cjs/common/grid' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/cjs/common' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/cjs/common/internal/directionUtils' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/cjs/common/internal/focusedCellUtils' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/cjs/common/internal/platformUtils' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/cjs/common/internal/scrollUtils' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/cjs/common/internal/selectionUtils' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/cjs/common/loadableContent' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/cjs/common/movementDelta' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/cjs/common/rect' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/cjs/common/renderMode' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/cjs/common/requestIdleCallback' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/cjs/common/utils' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/cjs/headers/columnHeader' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/cjs/headers/columnHeaderCell' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/cjs/headers/editableName' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/cjs/headers/header' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/cjs/headers/headerCell' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/cjs/headers/rowHeader' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/cjs/headers/rowHeaderCell' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/cjs' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/cjs/interactions/dragEvents' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/cjs/interactions/draggable' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/cjs/interactions/menus/copyCellsMenuItem' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/cjs/interactions/menus' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/cjs/interactions/menus/menuContext' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/cjs/interactions/reorderable' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/cjs/interactions/resizable' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/cjs/interactions/resizeHandle' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/cjs/interactions/resizeSensor' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/cjs/interactions/selectable' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/cjs/layers/guides' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/cjs/layers/regions' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/cjs/locator' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/cjs/quadrants/tableQuadrant' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/cjs/quadrants/tableQuadrantStack' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/cjs/quadrants/tableQuadrantStackCache' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/cjs/regions' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/cjs/table' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/cjs/tableBody' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/cjs/tableBodyCells' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esm/cell/cell' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esm/cell/editableCell' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esm/cell/formats/jsonFormat' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esm/cell/formats/truncatedFormat' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esm/column' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esm/common/batcher' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esm/common/cell' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esm/common/classes' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esm/common/clipboard' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esm/common/context' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esm/common/contextMenuTargetWrapper' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esm/common/direction' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esm/common/errors' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esm/common/grid' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esm/common' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esm/common/internal/directionUtils' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esm/common/internal/focusedCellUtils' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esm/common/internal/platformUtils' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esm/common/internal/scrollUtils' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esm/common/internal/selectionUtils' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esm/common/loadableContent' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esm/common/movementDelta' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esm/common/rect' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esm/common/renderMode' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esm/common/requestIdleCallback' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esm/common/utils' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esm/headers/columnHeader' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esm/headers/columnHeaderCell' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esm/headers/editableName' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esm/headers/header' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esm/headers/headerCell' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esm/headers/rowHeader' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esm/headers/rowHeaderCell' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esm' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esm/interactions/dragEvents' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esm/interactions/draggable' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esm/interactions/menus/copyCellsMenuItem' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esm/interactions/menus' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esm/interactions/menus/menuContext' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esm/interactions/reorderable' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esm/interactions/resizable' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esm/interactions/resizeHandle' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esm/interactions/resizeSensor' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esm/interactions/selectable' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esm/layers/guides' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esm/layers/regions' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esm/locator' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esm/quadrants/tableQuadrant' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esm/quadrants/tableQuadrantStack' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esm/quadrants/tableQuadrantStackCache' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esm/regions' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esm/table' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esm/tableBody' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esm/tableBodyCells' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esnext/cell/cell' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esnext/cell/editableCell' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esnext/cell/formats/jsonFormat' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esnext/cell/formats/truncatedFormat' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esnext/column' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esnext/common/batcher' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esnext/common/cell' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esnext/common/classes' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esnext/common/clipboard' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esnext/common/context' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esnext/common/contextMenuTargetWrapper' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esnext/common/direction' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esnext/common/errors' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esnext/common/grid' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esnext/common' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esnext/common/internal/directionUtils' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esnext/common/internal/focusedCellUtils' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esnext/common/internal/platformUtils' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esnext/common/internal/scrollUtils' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esnext/common/internal/selectionUtils' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esnext/common/loadableContent' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esnext/common/movementDelta' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esnext/common/rect' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esnext/common/renderMode' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esnext/common/requestIdleCallback' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esnext/common/utils' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esnext/headers/columnHeader' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esnext/headers/columnHeaderCell' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esnext/headers/editableName' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esnext/headers/header' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esnext/headers/headerCell' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esnext/headers/rowHeader' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esnext/headers/rowHeaderCell' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esnext' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esnext/interactions/dragEvents' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esnext/interactions/draggable' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esnext/interactions/menus/copyCellsMenuItem' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esnext/interactions/menus' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esnext/interactions/menus/menuContext' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esnext/interactions/reorderable' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esnext/interactions/resizable' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esnext/interactions/resizeHandle' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esnext/interactions/resizeSensor' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esnext/interactions/selectable' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esnext/layers/guides' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esnext/layers/regions' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esnext/locator' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esnext/quadrants/tableQuadrant' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esnext/quadrants/tableQuadrantStack' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esnext/quadrants/tableQuadrantStackCache' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esnext/regions' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esnext/table' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esnext/tableBody' {
  declare module.exports: any;
}

declare module '@blueprintjs/table/lib/esnext/tableBodyCells' {
  declare module.exports: any;
}

// Filename aliases
declare module '@blueprintjs/table/dist/table.bundle.js' {
  declare module.exports: $Exports<'@blueprintjs/table/dist/table.bundle'>;
}
declare module '@blueprintjs/table/lib/cjs/cell/cell.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/cjs/cell/cell'>;
}
declare module '@blueprintjs/table/lib/cjs/cell/editableCell.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/cjs/cell/editableCell'>;
}
declare module '@blueprintjs/table/lib/cjs/cell/formats/jsonFormat.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/cjs/cell/formats/jsonFormat'>;
}
declare module '@blueprintjs/table/lib/cjs/cell/formats/truncatedFormat.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/cjs/cell/formats/truncatedFormat'>;
}
declare module '@blueprintjs/table/lib/cjs/column.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/cjs/column'>;
}
declare module '@blueprintjs/table/lib/cjs/common/batcher.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/cjs/common/batcher'>;
}
declare module '@blueprintjs/table/lib/cjs/common/cell.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/cjs/common/cell'>;
}
declare module '@blueprintjs/table/lib/cjs/common/classes.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/cjs/common/classes'>;
}
declare module '@blueprintjs/table/lib/cjs/common/clipboard.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/cjs/common/clipboard'>;
}
declare module '@blueprintjs/table/lib/cjs/common/context.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/cjs/common/context'>;
}
declare module '@blueprintjs/table/lib/cjs/common/contextMenuTargetWrapper.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/cjs/common/contextMenuTargetWrapper'>;
}
declare module '@blueprintjs/table/lib/cjs/common/direction.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/cjs/common/direction'>;
}
declare module '@blueprintjs/table/lib/cjs/common/errors.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/cjs/common/errors'>;
}
declare module '@blueprintjs/table/lib/cjs/common/grid.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/cjs/common/grid'>;
}
declare module '@blueprintjs/table/lib/cjs/common/index' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/cjs/common'>;
}
declare module '@blueprintjs/table/lib/cjs/common/index.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/cjs/common'>;
}
declare module '@blueprintjs/table/lib/cjs/common/internal/directionUtils.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/cjs/common/internal/directionUtils'>;
}
declare module '@blueprintjs/table/lib/cjs/common/internal/focusedCellUtils.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/cjs/common/internal/focusedCellUtils'>;
}
declare module '@blueprintjs/table/lib/cjs/common/internal/platformUtils.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/cjs/common/internal/platformUtils'>;
}
declare module '@blueprintjs/table/lib/cjs/common/internal/scrollUtils.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/cjs/common/internal/scrollUtils'>;
}
declare module '@blueprintjs/table/lib/cjs/common/internal/selectionUtils.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/cjs/common/internal/selectionUtils'>;
}
declare module '@blueprintjs/table/lib/cjs/common/loadableContent.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/cjs/common/loadableContent'>;
}
declare module '@blueprintjs/table/lib/cjs/common/movementDelta.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/cjs/common/movementDelta'>;
}
declare module '@blueprintjs/table/lib/cjs/common/rect.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/cjs/common/rect'>;
}
declare module '@blueprintjs/table/lib/cjs/common/renderMode.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/cjs/common/renderMode'>;
}
declare module '@blueprintjs/table/lib/cjs/common/requestIdleCallback.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/cjs/common/requestIdleCallback'>;
}
declare module '@blueprintjs/table/lib/cjs/common/utils.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/cjs/common/utils'>;
}
declare module '@blueprintjs/table/lib/cjs/headers/columnHeader.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/cjs/headers/columnHeader'>;
}
declare module '@blueprintjs/table/lib/cjs/headers/columnHeaderCell.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/cjs/headers/columnHeaderCell'>;
}
declare module '@blueprintjs/table/lib/cjs/headers/editableName.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/cjs/headers/editableName'>;
}
declare module '@blueprintjs/table/lib/cjs/headers/header.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/cjs/headers/header'>;
}
declare module '@blueprintjs/table/lib/cjs/headers/headerCell.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/cjs/headers/headerCell'>;
}
declare module '@blueprintjs/table/lib/cjs/headers/rowHeader.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/cjs/headers/rowHeader'>;
}
declare module '@blueprintjs/table/lib/cjs/headers/rowHeaderCell.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/cjs/headers/rowHeaderCell'>;
}
declare module '@blueprintjs/table/lib/cjs/index' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/cjs'>;
}
declare module '@blueprintjs/table/lib/cjs/index.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/cjs'>;
}
declare module '@blueprintjs/table/lib/cjs/interactions/dragEvents.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/cjs/interactions/dragEvents'>;
}
declare module '@blueprintjs/table/lib/cjs/interactions/draggable.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/cjs/interactions/draggable'>;
}
declare module '@blueprintjs/table/lib/cjs/interactions/menus/copyCellsMenuItem.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/cjs/interactions/menus/copyCellsMenuItem'>;
}
declare module '@blueprintjs/table/lib/cjs/interactions/menus/index' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/cjs/interactions/menus'>;
}
declare module '@blueprintjs/table/lib/cjs/interactions/menus/index.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/cjs/interactions/menus'>;
}
declare module '@blueprintjs/table/lib/cjs/interactions/menus/menuContext.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/cjs/interactions/menus/menuContext'>;
}
declare module '@blueprintjs/table/lib/cjs/interactions/reorderable.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/cjs/interactions/reorderable'>;
}
declare module '@blueprintjs/table/lib/cjs/interactions/resizable.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/cjs/interactions/resizable'>;
}
declare module '@blueprintjs/table/lib/cjs/interactions/resizeHandle.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/cjs/interactions/resizeHandle'>;
}
declare module '@blueprintjs/table/lib/cjs/interactions/resizeSensor.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/cjs/interactions/resizeSensor'>;
}
declare module '@blueprintjs/table/lib/cjs/interactions/selectable.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/cjs/interactions/selectable'>;
}
declare module '@blueprintjs/table/lib/cjs/layers/guides.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/cjs/layers/guides'>;
}
declare module '@blueprintjs/table/lib/cjs/layers/regions.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/cjs/layers/regions'>;
}
declare module '@blueprintjs/table/lib/cjs/locator.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/cjs/locator'>;
}
declare module '@blueprintjs/table/lib/cjs/quadrants/tableQuadrant.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/cjs/quadrants/tableQuadrant'>;
}
declare module '@blueprintjs/table/lib/cjs/quadrants/tableQuadrantStack.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/cjs/quadrants/tableQuadrantStack'>;
}
declare module '@blueprintjs/table/lib/cjs/quadrants/tableQuadrantStackCache.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/cjs/quadrants/tableQuadrantStackCache'>;
}
declare module '@blueprintjs/table/lib/cjs/regions.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/cjs/regions'>;
}
declare module '@blueprintjs/table/lib/cjs/table.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/cjs/table'>;
}
declare module '@blueprintjs/table/lib/cjs/tableBody.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/cjs/tableBody'>;
}
declare module '@blueprintjs/table/lib/cjs/tableBodyCells.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/cjs/tableBodyCells'>;
}
declare module '@blueprintjs/table/lib/esm/cell/cell.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esm/cell/cell'>;
}
declare module '@blueprintjs/table/lib/esm/cell/editableCell.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esm/cell/editableCell'>;
}
declare module '@blueprintjs/table/lib/esm/cell/formats/jsonFormat.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esm/cell/formats/jsonFormat'>;
}
declare module '@blueprintjs/table/lib/esm/cell/formats/truncatedFormat.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esm/cell/formats/truncatedFormat'>;
}
declare module '@blueprintjs/table/lib/esm/column.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esm/column'>;
}
declare module '@blueprintjs/table/lib/esm/common/batcher.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esm/common/batcher'>;
}
declare module '@blueprintjs/table/lib/esm/common/cell.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esm/common/cell'>;
}
declare module '@blueprintjs/table/lib/esm/common/classes.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esm/common/classes'>;
}
declare module '@blueprintjs/table/lib/esm/common/clipboard.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esm/common/clipboard'>;
}
declare module '@blueprintjs/table/lib/esm/common/context.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esm/common/context'>;
}
declare module '@blueprintjs/table/lib/esm/common/contextMenuTargetWrapper.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esm/common/contextMenuTargetWrapper'>;
}
declare module '@blueprintjs/table/lib/esm/common/direction.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esm/common/direction'>;
}
declare module '@blueprintjs/table/lib/esm/common/errors.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esm/common/errors'>;
}
declare module '@blueprintjs/table/lib/esm/common/grid.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esm/common/grid'>;
}
declare module '@blueprintjs/table/lib/esm/common/index' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esm/common'>;
}
declare module '@blueprintjs/table/lib/esm/common/index.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esm/common'>;
}
declare module '@blueprintjs/table/lib/esm/common/internal/directionUtils.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esm/common/internal/directionUtils'>;
}
declare module '@blueprintjs/table/lib/esm/common/internal/focusedCellUtils.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esm/common/internal/focusedCellUtils'>;
}
declare module '@blueprintjs/table/lib/esm/common/internal/platformUtils.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esm/common/internal/platformUtils'>;
}
declare module '@blueprintjs/table/lib/esm/common/internal/scrollUtils.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esm/common/internal/scrollUtils'>;
}
declare module '@blueprintjs/table/lib/esm/common/internal/selectionUtils.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esm/common/internal/selectionUtils'>;
}
declare module '@blueprintjs/table/lib/esm/common/loadableContent.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esm/common/loadableContent'>;
}
declare module '@blueprintjs/table/lib/esm/common/movementDelta.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esm/common/movementDelta'>;
}
declare module '@blueprintjs/table/lib/esm/common/rect.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esm/common/rect'>;
}
declare module '@blueprintjs/table/lib/esm/common/renderMode.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esm/common/renderMode'>;
}
declare module '@blueprintjs/table/lib/esm/common/requestIdleCallback.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esm/common/requestIdleCallback'>;
}
declare module '@blueprintjs/table/lib/esm/common/utils.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esm/common/utils'>;
}
declare module '@blueprintjs/table/lib/esm/headers/columnHeader.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esm/headers/columnHeader'>;
}
declare module '@blueprintjs/table/lib/esm/headers/columnHeaderCell.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esm/headers/columnHeaderCell'>;
}
declare module '@blueprintjs/table/lib/esm/headers/editableName.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esm/headers/editableName'>;
}
declare module '@blueprintjs/table/lib/esm/headers/header.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esm/headers/header'>;
}
declare module '@blueprintjs/table/lib/esm/headers/headerCell.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esm/headers/headerCell'>;
}
declare module '@blueprintjs/table/lib/esm/headers/rowHeader.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esm/headers/rowHeader'>;
}
declare module '@blueprintjs/table/lib/esm/headers/rowHeaderCell.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esm/headers/rowHeaderCell'>;
}
declare module '@blueprintjs/table/lib/esm/index' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esm'>;
}
declare module '@blueprintjs/table/lib/esm/index.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esm'>;
}
declare module '@blueprintjs/table/lib/esm/interactions/dragEvents.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esm/interactions/dragEvents'>;
}
declare module '@blueprintjs/table/lib/esm/interactions/draggable.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esm/interactions/draggable'>;
}
declare module '@blueprintjs/table/lib/esm/interactions/menus/copyCellsMenuItem.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esm/interactions/menus/copyCellsMenuItem'>;
}
declare module '@blueprintjs/table/lib/esm/interactions/menus/index' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esm/interactions/menus'>;
}
declare module '@blueprintjs/table/lib/esm/interactions/menus/index.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esm/interactions/menus'>;
}
declare module '@blueprintjs/table/lib/esm/interactions/menus/menuContext.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esm/interactions/menus/menuContext'>;
}
declare module '@blueprintjs/table/lib/esm/interactions/reorderable.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esm/interactions/reorderable'>;
}
declare module '@blueprintjs/table/lib/esm/interactions/resizable.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esm/interactions/resizable'>;
}
declare module '@blueprintjs/table/lib/esm/interactions/resizeHandle.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esm/interactions/resizeHandle'>;
}
declare module '@blueprintjs/table/lib/esm/interactions/resizeSensor.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esm/interactions/resizeSensor'>;
}
declare module '@blueprintjs/table/lib/esm/interactions/selectable.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esm/interactions/selectable'>;
}
declare module '@blueprintjs/table/lib/esm/layers/guides.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esm/layers/guides'>;
}
declare module '@blueprintjs/table/lib/esm/layers/regions.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esm/layers/regions'>;
}
declare module '@blueprintjs/table/lib/esm/locator.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esm/locator'>;
}
declare module '@blueprintjs/table/lib/esm/quadrants/tableQuadrant.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esm/quadrants/tableQuadrant'>;
}
declare module '@blueprintjs/table/lib/esm/quadrants/tableQuadrantStack.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esm/quadrants/tableQuadrantStack'>;
}
declare module '@blueprintjs/table/lib/esm/quadrants/tableQuadrantStackCache.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esm/quadrants/tableQuadrantStackCache'>;
}
declare module '@blueprintjs/table/lib/esm/regions.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esm/regions'>;
}
declare module '@blueprintjs/table/lib/esm/table.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esm/table'>;
}
declare module '@blueprintjs/table/lib/esm/tableBody.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esm/tableBody'>;
}
declare module '@blueprintjs/table/lib/esm/tableBodyCells.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esm/tableBodyCells'>;
}
declare module '@blueprintjs/table/lib/esnext/cell/cell.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esnext/cell/cell'>;
}
declare module '@blueprintjs/table/lib/esnext/cell/editableCell.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esnext/cell/editableCell'>;
}
declare module '@blueprintjs/table/lib/esnext/cell/formats/jsonFormat.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esnext/cell/formats/jsonFormat'>;
}
declare module '@blueprintjs/table/lib/esnext/cell/formats/truncatedFormat.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esnext/cell/formats/truncatedFormat'>;
}
declare module '@blueprintjs/table/lib/esnext/column.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esnext/column'>;
}
declare module '@blueprintjs/table/lib/esnext/common/batcher.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esnext/common/batcher'>;
}
declare module '@blueprintjs/table/lib/esnext/common/cell.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esnext/common/cell'>;
}
declare module '@blueprintjs/table/lib/esnext/common/classes.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esnext/common/classes'>;
}
declare module '@blueprintjs/table/lib/esnext/common/clipboard.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esnext/common/clipboard'>;
}
declare module '@blueprintjs/table/lib/esnext/common/context.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esnext/common/context'>;
}
declare module '@blueprintjs/table/lib/esnext/common/contextMenuTargetWrapper.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esnext/common/contextMenuTargetWrapper'>;
}
declare module '@blueprintjs/table/lib/esnext/common/direction.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esnext/common/direction'>;
}
declare module '@blueprintjs/table/lib/esnext/common/errors.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esnext/common/errors'>;
}
declare module '@blueprintjs/table/lib/esnext/common/grid.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esnext/common/grid'>;
}
declare module '@blueprintjs/table/lib/esnext/common/index' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esnext/common'>;
}
declare module '@blueprintjs/table/lib/esnext/common/index.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esnext/common'>;
}
declare module '@blueprintjs/table/lib/esnext/common/internal/directionUtils.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esnext/common/internal/directionUtils'>;
}
declare module '@blueprintjs/table/lib/esnext/common/internal/focusedCellUtils.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esnext/common/internal/focusedCellUtils'>;
}
declare module '@blueprintjs/table/lib/esnext/common/internal/platformUtils.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esnext/common/internal/platformUtils'>;
}
declare module '@blueprintjs/table/lib/esnext/common/internal/scrollUtils.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esnext/common/internal/scrollUtils'>;
}
declare module '@blueprintjs/table/lib/esnext/common/internal/selectionUtils.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esnext/common/internal/selectionUtils'>;
}
declare module '@blueprintjs/table/lib/esnext/common/loadableContent.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esnext/common/loadableContent'>;
}
declare module '@blueprintjs/table/lib/esnext/common/movementDelta.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esnext/common/movementDelta'>;
}
declare module '@blueprintjs/table/lib/esnext/common/rect.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esnext/common/rect'>;
}
declare module '@blueprintjs/table/lib/esnext/common/renderMode.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esnext/common/renderMode'>;
}
declare module '@blueprintjs/table/lib/esnext/common/requestIdleCallback.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esnext/common/requestIdleCallback'>;
}
declare module '@blueprintjs/table/lib/esnext/common/utils.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esnext/common/utils'>;
}
declare module '@blueprintjs/table/lib/esnext/headers/columnHeader.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esnext/headers/columnHeader'>;
}
declare module '@blueprintjs/table/lib/esnext/headers/columnHeaderCell.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esnext/headers/columnHeaderCell'>;
}
declare module '@blueprintjs/table/lib/esnext/headers/editableName.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esnext/headers/editableName'>;
}
declare module '@blueprintjs/table/lib/esnext/headers/header.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esnext/headers/header'>;
}
declare module '@blueprintjs/table/lib/esnext/headers/headerCell.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esnext/headers/headerCell'>;
}
declare module '@blueprintjs/table/lib/esnext/headers/rowHeader.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esnext/headers/rowHeader'>;
}
declare module '@blueprintjs/table/lib/esnext/headers/rowHeaderCell.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esnext/headers/rowHeaderCell'>;
}
declare module '@blueprintjs/table/lib/esnext/index' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esnext'>;
}
declare module '@blueprintjs/table/lib/esnext/index.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esnext'>;
}
declare module '@blueprintjs/table/lib/esnext/interactions/dragEvents.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esnext/interactions/dragEvents'>;
}
declare module '@blueprintjs/table/lib/esnext/interactions/draggable.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esnext/interactions/draggable'>;
}
declare module '@blueprintjs/table/lib/esnext/interactions/menus/copyCellsMenuItem.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esnext/interactions/menus/copyCellsMenuItem'>;
}
declare module '@blueprintjs/table/lib/esnext/interactions/menus/index' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esnext/interactions/menus'>;
}
declare module '@blueprintjs/table/lib/esnext/interactions/menus/index.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esnext/interactions/menus'>;
}
declare module '@blueprintjs/table/lib/esnext/interactions/menus/menuContext.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esnext/interactions/menus/menuContext'>;
}
declare module '@blueprintjs/table/lib/esnext/interactions/reorderable.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esnext/interactions/reorderable'>;
}
declare module '@blueprintjs/table/lib/esnext/interactions/resizable.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esnext/interactions/resizable'>;
}
declare module '@blueprintjs/table/lib/esnext/interactions/resizeHandle.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esnext/interactions/resizeHandle'>;
}
declare module '@blueprintjs/table/lib/esnext/interactions/resizeSensor.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esnext/interactions/resizeSensor'>;
}
declare module '@blueprintjs/table/lib/esnext/interactions/selectable.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esnext/interactions/selectable'>;
}
declare module '@blueprintjs/table/lib/esnext/layers/guides.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esnext/layers/guides'>;
}
declare module '@blueprintjs/table/lib/esnext/layers/regions.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esnext/layers/regions'>;
}
declare module '@blueprintjs/table/lib/esnext/locator.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esnext/locator'>;
}
declare module '@blueprintjs/table/lib/esnext/quadrants/tableQuadrant.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esnext/quadrants/tableQuadrant'>;
}
declare module '@blueprintjs/table/lib/esnext/quadrants/tableQuadrantStack.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esnext/quadrants/tableQuadrantStack'>;
}
declare module '@blueprintjs/table/lib/esnext/quadrants/tableQuadrantStackCache.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esnext/quadrants/tableQuadrantStackCache'>;
}
declare module '@blueprintjs/table/lib/esnext/regions.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esnext/regions'>;
}
declare module '@blueprintjs/table/lib/esnext/table.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esnext/table'>;
}
declare module '@blueprintjs/table/lib/esnext/tableBody.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esnext/tableBody'>;
}
declare module '@blueprintjs/table/lib/esnext/tableBodyCells.js' {
  declare module.exports: $Exports<'@blueprintjs/table/lib/esnext/tableBodyCells'>;
}
